### ISSUE TITLE
DB Model

### ISSUE THREAD

**Issue by smartcuc** [leopoul/covid19_grafana#1]
Well done. 
Maybe you can help me to understand the database model you have created. Trying to get hands on that.
Many thanks!!

**Comment by helterskelter01** [comment]
Thank for an awesome grafana display. However there seems to be some kind of error with the maps since I am not getting the red/green/orange dots on the map.

**Comment by leopoul** [comment]
The InfluxDB measurement is called covid19.

Tags: country, province and location. Country and Province come from the API (https://github.com/ExpDev07/coronavirus-tracker-api) whereas location is the concatenation of country and province: https://github.com/leopoul/covid19_grafana/blob/master/app.py#L119

Fields:
Confirmed, Deaths, Recovered. 
Let me know if you need more info.
