### ISSUE TITLE
red/green/orange dots on the map not appearing

### ISSUE THREAD

**Issue by helterskelter01** [leopoul/covid19_grafana#2]
Thank for an awesome grafana display. However there seems to be some kind of error with the maps since I am not getting the red/green/orange dots on the map.

**Comment by leopoul** [comment]
I get that sometimes. Try these:
1. Try on a different browser
2. Try to adjust the time period, eg. got from last 30 days to last 7 days and see if that works
3. Open the browser developer console and look for Error messages.

**Comment by leopoul** [comment]
The other thing that could happen is that you run the containers on a server. The thing with this dashboard is that it's using the map plugin with a JSON locations endpoint. As the data fetching is taking place on the client side (your browser) if you have setup the environment on a server then the hardcoded locations URL (http://locahost....) is not reachable. I can look into improving this somehow. Unfortunately, Grafana dashboard provisioning does not support variables at the moment.

**Comment by Corruptsector** [comment]
Thanks for this project. Very Cool. You can just fix this issue by replacing localhost with the IP address of the server if running on a server, it wont work for everyone but it gets it going.
