### ISSUE TITLE
covid19_grafana_web_1 exited with code 1

### ISSUE THREAD

**Issue by mphp** [leopoul/covid19_grafana#3]
Hello,
When I start the containers I get :

_covid19_grafana_web_1 exited with code 1_

and the logs mentions :

_standard_init_linux.go:211: exec user process caused "exec format error",_

Any idea why ? 
I run it on a raspberry pi

**Comment by leopoul** [comment]
This is a clear indication that you need to go for a different docker image tailored to ARM architecture
